# Generated by Django 4.2.13 on 2024-07-08 06:14

import core.model_fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_profile_birth_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='birth_date',
            field=core.model_fields.DatePickerField(blank=True, null=True),
        ),
    ]
