# Generated by Django 4.2.13 on 2024-06-18 06:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_auto_20240618_0621'),
    ]

    operations = [
    ]
