# Generated by Django 4.2.13 on 2024-07-08 05:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_profile_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='phone_number',
            field=models.CharField(blank=True, max_length=13, validators=[django.core.validators.RegexValidator('^01\\d[ -]?\\d{4}[ -]?\\d{4}$', message='휴대폰 번호 포맷으로 입력해주세요.')]),
        ),
    ]
