# Generated by Django 4.2.13 on 2024-07-01 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_alter_review_table_comment'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='tag',
            name='blog_tag_name_43b6ed_idx',
        ),
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
