# Generated by Django 4.2.13 on 2024-06-26 01:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_accesslog_created_at_accesslog_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'permissions': [('view_premium_post', '프리미엄 컨텐츠를 볼 수 있음')], 'verbose_name': '포스팅', 'verbose_name_plural': '포스팅 목록'},
        ),
    ]
